### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO23_Mission_Engage_Resentment_1A.WL_Rosche#1]
### Mission:
 - [x] Российская доктрина предполагает что командир взвода это отряд 0, т.е. в миссии должно быть 210, а не 216
 - [x] А шо если 2 снайперов придать в 1-0, а в синих оставить автоматчиков\гпшников?
 - [x] `HMMWV`, а не `HMMVW`
 - [x]  Брифинг: Враждебные силы: Не раскрыта информация о том где противник и что будет делать, про вертолеты и бронетехнику обязательно пояснить (набегать на ан-64 с тепловизорами голой жопой довольно странно).
 - [x]  Странное название обжектива - МОСТ, когда на карте 3 моста, как отличить что говорят про мост, а не про МОСТ, и наоборот?
 - [x]  Добавить М2 на высоком станке в окопные бункеры? 
 - [x] Вообще оборона крайне жидко смотрится, может поставить танчики в обыспке хотя бы по 1 на мост, чтото уровня м60/бредли, + ТОУки статики и на хамви, все таки орды т72 ожидаются), а экипаж в окопные комантки. Типа зевс если успеет их проснет и до танчика добежит, но можно их легко выпилить пихотой. Плюс какие бетонные блоки на мостах, так то русня сходу переплывать будет, но лишние палки в колеса пущай будут

### Dynai:

-------

Предлагаю переделать задачи следующим образом:

Мосты изначально заминированы пиндосами (чтобы на случай проеба наступления их взрывать). Нам нужно заряды снять и, по возможности, обезвредить наблюдательный пункт (где сидят арт.корректировщики и может даже ТОУ-2 стоит).
Чтобы это сделать нам сначала нужно устроить диверсию в тылу пиндосов. Целями для диверсий могут служить:
а) Контр-батарейный радар (его уничтожение позволит в дальнейшем использовать арт поддержку)
б) Склад боеприпасов или ГСМ или FARP (взорвать руками или навести арту)
в) Позицию ПВО Avengers или артиллерию (взорвать руками или навести арту)
г) Минирование supply road (накидать мин, по сути доп таска чтобы возродить погибших и чтобы зевсу смешнее было ехать к мостам)
После совершения диверсий - в тылу начинают ерзать подкрепы и к мостам поедут только через некоторое время (когда убедятся, что прочие важные точки в тылу защищены и в окрестностях никто больше не лазит, чем больше диверсий было совершенно, тем больше времени враг будет занят патрулированием тылов). За это время игрокам и следует выйти к мосту, снять НП, снять заряды и, если бой уже начался, удерживать позиции до прихода подкрепов (к этому моменту миссия уже выполнена, ласт стенд просто бонус).

В тылу могут находиться небольшие КП (хамвик и фаертима пацанов тормозящие всяких левых гражданских), а также могут ездить хамвики по штабным делам. Их можно будет залутать, чтобы передвигаться быстрее.

**Comment by OneScheer** [comment]
Идея крутая, но:

1) Как сделать использование арты только после уничтожения радара.
2) Как управлять подкрепами, сколько их спавнить. Смутно себе представляю это скриптами
3) Как сделать зависимость подкреплений от числа диверсий

**Comment by 10Dozen** [comment]
1) В процессе, будет доступно в tSF 2.04
2) Тащемта делаешь дунай зону и поведение Vehicle Advance, как взорвалось чонить - поехали на точку подкрепы
3) См. п.2, ну или ГСО будет играть против игроков, т.к. по сути ЗА игроков делать нечего, поддержки у игроков не будет кроме той что они сами могут заказать

**Comment by OneScheer** [comment]
### Mission:
1. Название слота командира исправлено.
2. Снайперы приданы к командному отделению.
3. Исправлено.
4. Переписан брифинг, информация о противнике собрана в пункте враждебные силы.
5. Переделаны названия обжективов для аутентичности, аутистичности.
6.  Добавлены ассеты для обороны на основных обжективах.
7.  Добавлены брэдли и окопы для экипажа.
Добавлены доп.задачи для выполнения. Указан порядок выполнения в брифинге.

**Comment by 10Dozen** [comment]
### Mission:
 - [x] 1. Имя группы в игре осталось 216, переименуй в Callsign группы (на слое Playable Units)
 - [x] 2. В имени ролей у командиров %1, нужно бы подчистить (тут и в GAT/Authorization)
 - [x] 3. Было бы неплохо добавить в овервью упоминание "behind enemy lines", то есть "в тылу"
 - [x] 4. В дескрипшене пометить почему роли обязательные (типа несут взрывчатку или более общее - несут спец - [ ] .снаряжение), заодно вместо запятых использовать какие нить спецсимволы для разделения ролей
 - [x] 5. Можно отметить известные статичные позиции на карте маркером
 - [x] 6. Брифинг: Враждебные: "Подкрепления противника могут содержать" лучше заменить "В качестве подкреплений - механизированные подразделения и поддержка минометов"
 - [x] 7. Брифинг: Выполнение: Выдели фазы в отдельные абзацы для наглядности, про захват транспорта вообще в начале указать, но не "требуется", а "рекомендуется"
 - [x] 8. Брифинг - убрать лишние пустые строки (например в поддержке их там дофига в конце
 - [x] 9. Брифинг: Поддержка - рекомендую информацию давать блоками типа:
```
Ящик со снаряжением и амуницией на позиции ЕЛЕНА.

Артиллерия:
- 122мм батарея Д-30 - Буревестник-1-1 (доступна после уничтожения радара)

Редеплой/доукомплект:
- За счёт недоукомплектованных отрядов после выполнения любой из задач."
```
 - [x] 10. Заметки для гсо: А что такое offmap подкрепления? Они сами спавнятся или это те что снизу указаны? Алсо добавить указание, что кроме пары отрядов QRF остальные менее активны и не должны бросать свои позиции.
 - [x] 11. Брифинг - задачи - лучше сначала перечислить основные задачи, а потом уже дополнительные, и пометить что доп. задачи отвлекут силы, и в заметках для ГСО указать что после атак на обжективы в тылу он ДОЛЖЕН туда отправить наряд сил чтобы разобраться и начать search and destroy в районе
 - [x] 12. Какойто Ми-24 стоит на востоке
 - [x] 13. Добавить декораций (палаток, ящиков) и костров на позициях пиндосов в тылу (где ПВО, на КПП и проч), ночью ж холодно, хочца погрецца, каши поесть, и игрокам будет удобнее находить в зеленом месиве следы жизнедеятельности 
 - [x] 14. На АИСТ бредли стоит на окопе (предположу, что он "выстрелил" физоном из своего окопа и приземлился на бункер экипажа)

### tSF:
 - [x] 1. Луна не всю ночь в небе, если хочешь чтобы точно была - измени в initServer в определении MissionDate в case 1: { [21, 8] call _fnc_getRandomHrs }; укажи диапазон более точный - сейчас с 21 до 8 утра (до 9 по факту из-за того что минуты могут быть 0-55). Можно сделать 23, 3
 - [x] 2. Artillery:  осветительные миссии 12 миссий, а то ночь все таки

### Gear:
 - [x] 1. Чото не дали ПНВ, а темно как в сраке. Может АНПВС-7 выдать (типа залутаны) 
 - [x] 2. В ящике на базе непонятно зачем СВД и почему FirstAid Kits. Рекомендую убрать, добавить чисто турникетов и бинтов, положить подствольные и ручные сигнальные гранаты (от них должно быть чуть больше толку для целеуказания в ночи). Мне кажется есть смысл ПЗРК тоже туда положить, возможно он и не понадобиться, поэтому на усмотрение командира.
 - [x] 3. Немного смущает обилие НСПУ, может лучше выдать хуевенькие ПНВ, а командиру, старшему стрелку и еще паре рыл еще и НСПУ, остальные с айронсайтами
 - [x] 4. У Стрелка ПСО на калаше, в ночи врядли шото видно, а НСПУ с зумом
 - [x] 5. Снайперы с СВД, но возможно имеет смысл им Винторезы выдать (типа тихие), или один с СВД второй с ВСС.
 - [x] 6. ПНВ для ботов? Добавит как рандомный айтем типа ["NVG_Class","","","",""] - будет рандомно с 20% шансом

### Dynai:
 - [ ] 1. В initServer неправильно условие, нужно чтото типа (но оно не будет работать, т.к. поведение машины Advance предпологает что машина спавнится, едет воевать на кейпоинты, а на последнем останавливается и превращается в статичную огневую позицию, а статичные позиции функция moveGroups не может сдвинуть, так что лучше делай условие активации по человечески):
```
waitUntil { !isNil "dzn_dynai_initialized" && { dzn_dynai_initialized } };
[{ !alive TGT1 }, {
	reinf call dzn_fnc_dynai_activateZone;
	[{ [reinf, getPosATL RADAR, "SAD"] call dzn_fnc_dynai_moveGroups; }, [], 30] call CBA_fnc_waitAndExecute;
}] call CBA_fnc_waitUntilAndExecute;
```

Но вообще в Дунае можно заранее указать условие актвиации, в хелпере. Делаешь зону неактивной, пишешь свое условие активации, а юнитам пишешь режим - Advance (шото типа http://puu.sh/FoI19/b3ffdafbbb.png и http://puu.sh/FoI1n/9fb13e5eca.png )

 - [x] 2. Всем статичным пихотам новесить dynai indoor behaviour (он вроде подключает кеширование к ботам заодно)

----
Может стоит сделать слот медика в 210? Попробовать эдакий мобильные ЦЦП который может умереть?

**Comment by OneScheer** [comment]
По возможности исправил всё и добавил медика.

**Comment by 10Dozen** [comment]
Починить Dynai.1 и будет норм

А нехуя, у санитара не стоит Is Medic в свойствах. Открой Едит юнит в редакторе, Object: ACE Options > Is Medic = Doctor (наверное)

**Comment by OneScheer** [comment]
Починил Dynai
Добавил санитару доктора
Добавил ПСО-1-1 для ВСС
