### ISSUE TITLE
Ревью1

### ISSUE THREAD

**Issue by Comrade333** [rempopo/CO23_Mission_Engage_Resentment_1A.WL_Rosche#2]
1) Думаю лучше будет перенести стартовую точку восточнее, ближе к "ПЕРЕПЕЛУ", там как раз много леса еще, а то вангую мужики будут ныть, плюс миска достаточно долгая и богата на таски, не стоит мужикам раньше времени уставать.
2) На "Гусе" все ящики под открытым небом, хотя в паре метров есть большой и пустой ангар, который охраняет боец, может часть ящиком засунуть/машинок занать/сделать что-нибудь тип казармы внутри?
3) Добавил в рандом акмс (шоб прям спецназ был) если хочешь апрувни.
4) Укажи что в ящиках лежит игла, а то вдруг командир захочет устроить охоту на вертолет.

**Comment by OneScheer** [comment]
1.  Перенёс старт.
2. Добавил ящиков в здание.
3. Замерджил.
4. Добавил в брифинг.
